### ISSUE TITLE
Trouble with installing DPViewer

### ISSUE THREAD

**Issue by RaymonHE** [princeton-vl/DPVO#13]
Hi @lahavlipson @zachteed! 
Thanks for releasing such fancy and great work. 
I had trouble installing the DPViewer and everything works well before then, until this step. 
 After I inputting ""pip install ./DPViewer", the outcome was

> Processing ./DPViewer
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: dpviewer
  Building wheel for dpviewer (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [80 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      -- The CUDA compiler identification is NVIDIA 10.1.243
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /usr/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- Looking for pthread.h
      -- Looking for pthread.h - found
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Found CUDA: /usr (found version "10.1")
      -- Caffe2: CUDA detected: 10.1
      -- Caffe2: CUDA nvcc is: /usr/bin/nvcc
      -- Caffe2: CUDA toolkit directory: /usr
      CMake Error at /home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:55 (message):
        PyTorch requires CUDA 10.2 or above.
      Call Stack (most recent call first):
        /home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
        /home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
        CMakeLists.txt:24 (find_package)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/home/rui/workspace/DPVO/DPViewer/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeOutput.log".
      See also "/home/rui/workspace/DPVO/DPViewer/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/rui/workspace/DPVO/DPViewer/setup.py", line 123, in <module>
          setup(
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/rui/workspace/DPVO/DPViewer/setup.py", line 112, in build_extension
          subprocess.check_call(
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/home/rui/workspace/DPVO/DPViewer', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/rui/workspace/DPVO/DPViewer/build/lib.linux-x86_64-3.10/', '-DPYTHON_EXECUTABLE=/home/rui/anaconda3/envs/dpvo/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DTORCH_PATH=/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch', '-DEXAMPLE_VERSION_INFO=0.0.1']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dpviewer
  Running setup.py clean for dpviewer
Failed to build dpviewer
Installing collected packages: dpviewer
  Running setup.py install for dpviewer ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for dpviewer did not run successfully.
  │ exit code: 1
  ╰─> [100 lines of output]
      running install
      /home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/dpviewer
      copying dpviewer/__init__.py -> build/lib.linux-x86_64-3.10/dpviewer
      running build_ext
      -- The C compiler identification is GNU 9.4.0
      -- The CXX compiler identification is GNU 9.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- The CUDA compiler identification is NVIDIA 10.1.243
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /usr/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- Looking for pthread.h
      -- Looking for pthread.h - found
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Found CUDA: /usr (found version "10.1")
      -- Caffe2: CUDA detected: 10.1
      -- Caffe2: CUDA nvcc is: /usr/bin/nvcc
      -- Caffe2: CUDA toolkit directory: /usr
      CMake Error at /home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:55 (message):
        PyTorch requires CUDA 10.2 or above.
      Call Stack (most recent call first):
        /home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
        /home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
        CMakeLists.txt:24 (find_package)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/home/rui/workspace/DPVO/DPViewer/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeOutput.log".
      See also "/home/rui/workspace/DPVO/DPViewer/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/rui/workspace/DPVO/DPViewer/setup.py", line 123, in <module>
          setup(
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 664, in run
          self.run_command('build')
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/rui/workspace/DPVO/DPViewer/setup.py", line 112, in build_extension
          subprocess.check_call(
        File "/home/rui/anaconda3/envs/dpvo/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/home/rui/workspace/DPVO/DPViewer', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/rui/workspace/DPVO/DPViewer/build/lib.linux-x86_64-3.10/', '-DPYTHON_EXECUTABLE=/home/rui/anaconda3/envs/dpvo/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DTORCH_PATH=/home/rui/anaconda3/envs/dpvo/lib/python3.10/site-packages/torch', '-DEXAMPLE_VERSION_INFO=0.0.1']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dpviewer

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

I hope you can give me some more specific "hints"  since I've already followed the instruction listed and succeeded in installing the CUDA and cudnn. 

> nvidia-smi
Thu Nov 17 01:03:18 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 30%   46C    P0    26W / 120W |   1445MiB /  5120MiB |      7%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     22026      G   /usr/lib/xorg/Xorg                101MiB |
|    0   N/A  N/A     22595      G   /usr/lib/xorg/Xorg                816MiB |
|    0   N/A  N/A     22985      G   /usr/bin/gnome-shell              165MiB |
|    0   N/A  N/A     24264      G   ...150394509144825396,131072      286MiB |
+-----------------------------------------------------------------------------+

I searched for a while but didn't figure it out, so I wonder if you could do me a favor to help me find the problem. I appreciate it a lot.

**Comment by garybradski** [comment]
I get the same thing:
CMake Error at /home/colab/anaconda3/envs/dpvo/lib/python3.10/site-packages/cmake/data/share/cmake-3.22/Modules/CMakeTestCUDACompiler.cmake:56 (message):
        The CUDA compiler
      
          "/usr/bin/nvcc"
      
        is not able to compile a simple test program.
      
        It fails with the following output:
      
          Change Dir: /home/colab/code/DPVO/DPViewer/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeTmp
      
          Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_e03e9/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_e03e9.dir/build.make CMakeFiles/cmTC_e03e9.dir/build
          gmake[1]: Entering directory '/home/colab/code/DPVO/DPViewer/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeTmp'
          Building CUDA object CMakeFiles/cmTC_e03e9.dir/main.cu.o
          /usr/bin/nvcc      -c /home/colab/code/DPVO/DPViewer/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_e03e9.dir/main.cu.o
          ptxas /tmp/tmpxft_0024e7e0_00000000-6_main.ptx, line 9; fatal   : Unsupported .version 8.2; current version is '7.7'
          ptxas fatal   : Ptx assembly aborted due to errors
          gmake[1]: *** [CMakeFiles/cmTC_e03e9.dir/build.make:78: CMakeFiles/cmTC_e03e9.dir/main.cu.o] Error 255
          gmake[1]: Leaving directory '/home/colab/code/DPVO/DPViewer/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeTmp'
          gmake: *** [Makefile:127: cmTC_e03e9/fast] Error 2

Something about ptx wanting version 8.2 ptx?
